### ISSUE TITLE
What do you think of unicorns?

### ISSUE THREAD

**Issue by sindresorhus** [helenvholmes/ama#7]
![unicorn18](https://cloud.githubusercontent.com/assets/170270/25500506/7910bb56-2bb9-11e7-8f29-362404feb02a.gif)

**Comment by helenvholmes** [comment]
Sort of ambivalent, really. I know that's not an exciting answer by any means, but I think tech unicorns aren't real, people-unicorns are just humans with several interests, and designer-developers are just what happens when you gotta get some shit done, ya know?

**Comment by sindresorhus** [comment]
I meant unicorns as in the animal 😄

**Comment by helenvholmes** [comment]
@sindresorhus I think the answer might still be the same 😅
